portal/phd/routes.py
from flask import Flask,abort, session, render_template, url_for, flash, redirect, request,send_file, Blueprint
from portal import app, db
from portal.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required
import os 
import json
from os import path
import pandas as pd
import sqlite3
from datetime import datetime ,date ,timedelta


phds=Blueprint('phds',__name__,template_folder='templates')



@phds.route("/allocate_phd", methods=['GET', 'POST'])
@login_required
def allocate_phd():
    if current_user.is_active==True:
        if current_user.is_admin == True:
            conn = sqlite3.connect('portal/site.db') 
            c = conn.cursor()
            test=c.execute('''SELECT * FROM phd''').fetchall()
            test=[tup[::-1] for tup in test] 
            test = [list(ele) for ele in test] 
            user=User.query.all()
            def foo(user,test):
                i=0
                user_val=0
                phd_val=0
                flag1=1
                # for p in test:
                #     p[1]="1"
                for x in user:
                    if x.is_admin == False and x.is_manager == False and x.is_active == True:
                        user_val=user_val+1
                for pd in test:
                    phd_val=phd_val+1
                if user_val==0:
                    flash('No Tutor exists','danger')
                else:
                    quotient = phd_val//user_val 
                    remainder = phd_val%user_val 
                    #flash(phd_val)
                    
                    for p in test:
                        c.execute('''update phd set alloc_status = "0" WHERE Application = "'''+p[0]+'''";''')
                        conn.commit()
                        c.execute('''update phd set Tutor1 = "0" WHERE Application = "'''+p[0]+'''";''')
                        conn.commit()
                        
                    for u in user:
                        flag1=1
                        conn.commit()
                        i=0
                        conn.commit()
                        if u.is_admin==False and u.is_manager==False and u.is_active == True:
                            # print(u.username)
                            conn.commit()
                            for p in test:
                                # c.execute('''update phd set Tutor1 = "'''+p[1]+'''" WHERE Application = "'''+p[0]+'''";''')
                                # conn.commit()
                                if  i==quotient:
                                    if  remainder > 0 :
                                        flag1=0
                                        if p[1]=="0":
                                            p[1]="1"
                                            conn.commit()
                                            c.execute('''update phd set Tutor1 = "'''+u.username+'''" WHERE Application = "'''+p[0]+'''";''')
                                            conn.commit()
                                            c.execute('''update phd set alloc_status = "1" WHERE Application = "'''+p[0]+'''";''')
                                            conn.commit()
                                            remainder =remainder - 1
                                            flag1=1
                                    if  flag1 == 1:
                                        i=0
                                        break
                                if i<quotient and p[1]=="0" :
                                    p[1]="1"
                                    conn.commit()
                                    c.execute('''update phd set alloc_status = "1" WHERE Application = "'''+p[0]+'''";''')
                                    conn.commit()
                                    c.execute('''update phd set Tutor1 = "'''+u.username+'''" WHERE Application = "'''+p[0]+'''";''')
                                    conn.commit()
                                    c.execute('''update phd set alloc_status = "1" WHERE Application = "'''+p[0]+'''";''')
                                    conn.commit()
                                    i=i+1
                                conn.commit()
                    for p in test:
                        p[1]="1"
                    flag1=1
                    quotient = phd_val//user_val
                    remainder = phd_val%user_val
                    fla=0
                    i=0
                    for u in user:
                        flag1=1
                        if u.is_admin==False and u.is_manager==False and u.is_active == True :
                            if fla==1:
                                for p in test:
                                    if i==quotient:
                                        if remainder > 0 :
                                            flag1=0
                                            if p[1]=="1" and p[3] != u.username:
                                                p[1]="0"
                                                c.execute('''update phd set Tutor2 = "'''+u.username+'''" WHERE Application = "'''+p[0]+'''";''')
                                                conn.commit()
                                                c.execute('''update phd set alloc_status = "0" WHERE Application = "'''+p[0]+'''";''')
                                                conn.commit()
                                                remainder =remainder - 1
                                                flag1=1
                                        if flag1 == 1:
                                            i=0
                                            break
                                    if i<quotient and p[1]=="1" and p[3]!=u.username:
                                        p[1]="0"
                                        conn.commit()
                                        c.execute('''update phd set Tutor2 = "'''+u.username+'''" WHERE Application = "'''+p[0]+'''";''')
                                        conn.commit()
                                        c.execute('''update phd set alloc_status = "0" WHERE Application = "'''+p[0]+'''";''')
                                        conn.commit()
                                        i=i+1
                            fla=1
                        
                    flag1=1
                    fla=0
                    quotient = phd_val//user_val
                    i=0
                    for u in user:
                        flag1=1
                        if u.is_admin==False and u.is_manager==False and u.is_active == True:
                            for p in test:
                                if i==quotient:
                                    if remainder > 0 :
                                        flag1=0
                                        if p[1] =="1" and p[3] != u.username:
                                            p[1]="0"
                                            conn.commit()
                                            c.execute('''update phd set Tutor2 = "'''+u.username+'''" WHERE Application = "'''+p[0]+'''";''')
                                            conn.commit()
                                            c.execute('''update phd set alloc_status = "0" WHERE Application = "'''+p[0]+'''";''')
                                            conn.commit()
                                            remainder =remainder - 1
                                            flag1=1
                                    if flag1 == 1:
                                        i=0
                                        break
                                if i<quotient and p[1]=="1" and p[3]!=u.username:
                                    p[1]="0"
                                    conn.commit()
                                    c.execute('''update phd set Tutor2 = "'''+u.username+'''" WHERE Application = "'''+p[0]+'''";''')
                                    conn.commit()
                                    c.execute('''update phd set alloc_status = "0" WHERE Application = "'''+p[0]+'''";''')
                                    conn.commit()
                                    i=i+1
                            break
                    for pd in test:
                        pd[1]="1"
                    flash("Phd files allocated successfully","success")
            foo(user,test)
            return redirect(url_for('phds.phd'))
        else:
            report=str(current_user.username)+'  tried to accessed unauthorized route -> allocate_phd '
            fillReport(report,current_user.username,datetime.now())
            return render_template('error.html',error=404)
    else:
        flash('Your account has been deactivated by administrator','danger')
        return redirect(url_for('logout'))





@phds.route("/phdcsv", methods=['GET', 'POST'])
@login_required
def phdcsv():
    if current_user.is_active ==True:
        if current_user.is_admin == True:
            if path.exists("portal/static/original-csv/phd.csv"):
                conn = sqlite3.connect('portal/site.db') 
                c = conn.cursor()
                df=pd.read_csv('portal/static/original-csv/phd.csv')
                c.execute(''' SELECT count(name) FROM sqlite_master WHERE type='table' AND name='phd' ''')
                if c.fetchone()[0]==1 :
                    c.execute('''DROP TABLE phd;''')
                c.execute('''
                        CREATE TABLE phd (
                            "Application Ref. No." TEXT  PRIMARY KEY UNIQUE
                );''')
                new_columns=set(df.columns)
                new_columns.remove('Application Ref. No.')
                s=list(new_columns)
                for i in range(len(s)):
                    c.execute('''ALTER TABLE phd ADD'''+''' "'''+s[i]+'''" '''+'''TEXT''')

portal/templates/add_course.html
{% extends "layout.html" %}
{% block content %}

        <div class="container-fluid"> 
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                <div id="mydivs"  data-notify="container" class="col-xs-11 col-sm-4 alert alert-{{ category }} alert-with-icon animated fadeInDown" role="alert" data-notify-position="top-right" style="display: inline-block; margin: 15px auto; position: fixed; transition: all 0.5s ease-in-out 0s; z-index: 1031; top: 20px; right: 20px;">
                  <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close" style="position: absolute; right: 10px; top: 50%; margin-top: -9px; z-index: 1033;">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  <i data-notify="icon" class="material-icons">notifications</i>
                  <span data-notify="title"></span> 
                  <span data-notify="message">{{ message }}</span>
                </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            <script>
                setTimeout(function() {
                  $('#mydivs').fadeOut('slow');
              }, 2000);
              </script>
                <div class="col-sm-8 col-sm-offset-2">
                    <!--      Wizard container        -->
                    <div class="wizard-container">
                        <div class="card wizard-card active" data-color="rose" id="wizardProfile">
                            <form action="{{url_for('course')}}" method="POST" novalidate="novalidate">
                        <!--        You can switch " data-color="purple" "  with one of the next bright colors: "green", "orange", "red", "blue"       -->
            
                                <div class="wizard-header">
                                    <h3 class="wizard-title">
                                       Add New Course
                                    </h3>
                                    <h5>Make sure there is atleast one column with name "Application Ref. No."</h5>
                                </div>
                                <div class="wizard-navigation">
                                    <ul class="nav nav-pills">
                                        <li class="active" style="width: 33.3333%;"><a href="#about" data-toggle="tab" aria-expanded="true">About</a></li>
                                        
                                    </ul>
                                <div class="moving-tab" style="width: 203.588px; transform: translate3d(-8px, 0px, 0px); transition: transform 0s ease 0s;">About</div></div>
            
                                <div class="tab-content">
                                    <div class="tab-pane active" id="about">
                                      <div class="row">
                                            <h4 class="info-text"> Let's start with the basic information (with validation)</h4>
                                            
                                            <div class="col-sm-6">
                                                <div class="input-group">
                                                    <span class="input-group-addon">
                                                        <i class="material-icons">face</i>
                                                    </span>
                                                    <div class="form-group label-floating is-empty">
                                                      <label class="control-label">Course Name <small>(required)</small></label>
                                                      <input name="ncourse" type="text" class="form-control" onkeypress="return AvoidSpace(event)">
                                                      <input class="btn btn-rose btn-lg" type="submit" value="Add">
                                                    <span class="material-input"></span></div>
                                                </div>
            
                                                <script type="text/javascript">
                                                        function AvoidSpace(event) {
                                                            var k = event ? event.which : window.event.keyCode;
                                                            if (k <= 47|| (k>=58 && k<=64) || (k>=91 && k<=96)|| k>=123 ) 
                                                                return false;
                                                            
                                                                }


                                                </script>
                                            </div>
                                            
                                        </div>
                                    </div>
                                    
                                </div>
                                <div class="wizard-footer">
                                   
                                </div>
                            </form>
                        </div>
                    </div> <!-- wizard container -->
                </div>
        </div>
{% endblock content %}

portal/templates/announcements.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid">
                        {% with messages = get_flashed_messages(with_categories=true) %}
                          {% if messages %}
                            {% for category, message in messages %}
                            <div id="mydivs"  data-notify="container" class="col-xs-11 col-sm-4 alert alert-{{ category }} alert-with-icon animated fadeInDown" role="alert" data-notify-position="top-right" style="display: inline-block; margin: 15px auto; position: fixed; transition: all 0.5s ease-in-out 0s; z-index: 1031; top: 20px; right: 20px;">
                                <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close" style="position: absolute; right: 10px; top: 50%; margin-top: -9px; z-index: 1033;">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                                <i data-notify="icon" class="material-icons">notifications</i>
                                <span data-notify="title"></span> 
                                <span data-notify="message">{{ message }}</span>
                              </div>
                            {% endfor %}
                          {% endif %}
                        {% endwith %}
                        <script type="text/javascript">
                            setTimeout(function() {
                              $('#mydivs').fadeOut('slow');
                          }, 2700);
                          </script>
					 	    <div class="header text-center">
        <h3 class="title">Announcements</h3>
        <p class="category">All announcements will appear here</p>
                    
    </div>
    <div class="row" style="height: 80%;overflow: auto;">
        <div class="col-md-12">
            <div class="card card-plain">
                <div class="card-content">
                    <ul class="timeline">
                        {% for post in post%}
                        {% if post.id%2 != 0%}
                        <li class="timeline-inverted">
                            <div class="timeline-badge warning">
                                <i class="material-icons">flight_land</i>
                            </div>
                            <div class="timeline-panel" style="position: relative;">
                                <div class="timeline-heading">
                                    <span class="label label-warning">{{post.title}}</span>
                                </div>
                                <div class="timeline-body">
                                    <p>{{post.content}}</p>
                                </div>
                                
                            <div style="position:relative; width: 20%;left: 70%;top: 70%;">
                                <p>
                                    <i class="ti-time"></i>
                                    - <a href="{{ url_for( 'user',username=post.author.username )}}">{{post.author.username}} </a>
                                    </p>
                                    {% if post.author == current_user%}
                                    <a href="{{ url_for('delete_post', post_id=post.id) }}"><button data-toggle="modal" data-target="#deleteModal1" style="position: absolute;bottom: -40%;left: 80%;" class="btn btn-danger btn-round btn-fab btn-fab-mini">
                                        <i class="material-icons">delete</i>
                                        <div class="ripple-container"></div>
                                    </button></a>
                                   {% endif %}
                               </div>
                          </div>
                        </li>
                        {% else %}
                        <li>
                            <div class="timeline-badge info">
                                <i class="material-icons">extension</i>
                            </div>
                            <div class="timeline-panel" style="position: relative;">
                                <div class="timeline-heading">
                                  <span class="label label-info">{{post.title}}</span>
                                </div>
                                <div class="timeline-body">
                                    <p>{{post.content}}</p>
                                </div>
                                
                                <div style="position:relative; width: 20%;left: 70%;top: 70%;">
                                    <p>
                                        <i class="ti-time"></i>
                                        - <a href="{{ url_for( 'user',username=post.author.username )}}">{{post.author.username}} </a>
                                    </p>
                                    {% if post.author == current_user%}
                                    <a href="{{ url_for('delete_post', post_id=post.id) }}"><button style="position: absolute;bottom: -40%;left: 80%;" class="btn btn-danger btn-round btn-fab btn-fab-mini">
                                        <i class="material-icons">delete</i>
                                        <div class="ripple-container"></div>
                                    </button></a>
                                    {% endif %}
                                </div>
                            </div>
                        </li>
                        {% endif %}
                        {% endfor %}
                        
                    </ul>
                </div>
            </div>
        </div>
    </div>
   
    {% if current_user.is_admin==True or current_user.is_manager == True %}
                 
    <div class="col-md-6" style="width: 100%;position: relative;">
        <div class="card">
            <form  method="POST" action="" role="form">
                {{ form.hidden_tag() }}
                <div class="card-header card-header-icon" data-background-color="rose">
                    <i class="material-icons">contacts</i>
                </div>
                <div class="card-content" >
                    <h4 class="card-title">New Annoucement</h4>
                    <div class="form-group label-floating" style="width: 40%;">
                        <!-- <label class="control-label">Title</label> -->
                        {{ form.title.label(class="control-label") }}
                        {% if form.title.errors %}
                            {{ form.title(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.title.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.title(class="form-control") }}
                        {% endif %}
                        <!-- <input class="form-control" name="email" type="text" required="true" /> -->
                    </div>
                    <div class="form-group label-floating" style="width: 80%;">
                        <!-- <label class="control-label">Content</label> -->
                        {{ form.content.label(class="control-label") }}
                        {% if form.content.errors %}
                            {{ form.content(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class="form-control") }}
                        {% endif %}
                        <!-- <input class="form-control" name="password" type="text"required="true" /> -->
                    </div>

                    <div class="text-center" style="position: absolute; top: 60%;right: 3%;">
                        {{ form.submit(class="btn btn-rose btn-fill btn-wd") }}
                        <!-- <button type="submit" class="btn btn-rose btn-fill btn-wd" style="position: absolute; top: 60%;right: 3%;">Post</button> -->
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% endif %}
</div>
{% endblock content %}				

portal/templates/upload.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid">
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
      <div id="mydivs"  data-notify="container" class="col-xs-11 col-sm-4 alert alert-{{ category }} alert-with-icon animated fadeInDown" role="alert" data-notify-position="top-right" style="display: inline-block; margin: 15px auto; position: fixed; transition: all 0.5s ease-in-out 0s; z-index: 1031; top: 20px; right: 20px;">
          <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close" style="position: absolute; right: 10px; top: 50%; margin-top: -9px; z-index: 1033;">
            <span aria-hidden="true">&times;</span>
          </button>
          <i data-notify="icon" class="material-icons">notifications</i>
          <span data-notify="title"></span> 
          <span data-notify="message">{{ message }}</span>
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  <script>
      setTimeout(function() {
        $('#mydivs').fadeOut('slow');
    }, 2000);
    </script>
<div class="header text-center">
<h3 class="title">{{ title }}</h3>
<p class="category">Please upload files to their corresponding sections only!! </p>
</div>

<div class="row">
<div class="col-md-6">
<div class="card">
<div class="card-header" style="text-align: center;">
<h4 class="card-title">CSV Section</h4>
</div>
<div class="card-content" >


<div class="table-responsive table-sales" style="display: flex;justify-content: center; align-items: center;">
  <form action="{{url_for('upload_csv')}}" method="POST" enctype="multipart/form-data">
    <label value="Choose"  class="btn  btn-lg" id="wizard-picture"> 
      <input style="display: none;" type="file"  name="file" multiple  data-show-upload="true">
       Choose File
  </label>
      <!-- <button type="submit" class="btn btn-primary btn-lg"></button> -->
      
<div class="modal fade" id="smallAlertModalCsv" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-small ">
      <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="material-icons">clear</i></button>
          </div>
          <div class="modal-body text-center">
              <h5>Are you sure you want upload? </h5>
          </div>
          <div class="modal-footer text-center">
              <button type="button" class="btn btn-simple" data-dismiss="modal">Never mind</button>
              <button type="submit" class="btn btn-success btn-simple">Yes</button>
          </div>
      </div>
  </div>
</div>
  </form>
  
  
</div>
<div class="col-md-12 text-center">
<button class="btn btn-raised btn-round btn-rose" data-toggle="modal" data-target="#smallAlertModalCsv">
  Upload
</button>
</div>
</div>
</div>
</div>

<div class="col-md-6">
<div class="card">
<div class="card-header" style="text-align: center;">
<h4 class="card-title">PDF Section</h4>
</div>
<div class="card-content" >
  

<div class="table-responsive table-sales" style="display: flex;justify-content: center; align-items: center;">
  <form action="{{url_for('upload_pdf')}}" method="POST" enctype="multipart/form-data">
    <label value="Choose"  class="btn  btn-lg" id="wizard-picture"> 
      <input style="display: none;" type="file"  name="file" multiple  data-show-upload="true">
       Choose File
  </label>
      <!-- <button type="submit" class="btn btn-primary btn-lg"></button> -->
      
<div class="modal fade" id="smallAlertModalPdf" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-small ">
      <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="material-icons">clear</i></button>
          </div>
          <div class="modal-body text-center">
              <h5>Are you sure you want to upload? </h5>
          </div>
          <div class="modal-footer text-center">
              <button type="button" class="btn btn-simple" data-dismiss="modal">Never mind</button>
              <button type="submit" class="btn btn-success btn-simple">Yes</button>
          </div>
      </div>
  </div>
</div>
  </form>
  
  
</div>
<div class="col-md-12 text-center">
<button class="btn btn-raised btn-round btn-rose" data-toggle="modal" data-target="#smallAlertModalPdf">
  Upload
</button>
</div>
</div>
</div>
</div>
<div class="col-md-12">
<div class="card">
<div class="card-content">
<div class="places-buttons">
  <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center">
          <h4 class="card-title">
              Allocate Files
              <p class="category">Once allocated it can't be reverted</p>
          </h4>
      </div>
  </div>
  
</div>
<div class="modal fade" id="smallAlertModalphd" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-small ">
      <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="material-icons">clear</i></button>
          </div>
          <div class="modal-body text-center">
              <h5>Are you sure you want to submit? </h5>
          </div>
          <div class="modal-footer text-center">
              <button type="button" class="btn btn-simple" data-dismiss="modal">Never mind</button>
              <a href="{{url_for('phds.allocate_phd')}}"><button type="submit" class="btn btn-success btn-simple">Yes</button></a>
          </div>
      </div>
  </div>
</div>
<div class="modal fade" id="smallAlertModalmtech" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-small ">
      <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="material-icons">clear</i></button>
          </div>
          <div class="modal-body text-center">
              <h5>Are you sure you want to submit? </h5>
          </div>
          <div class="modal-footer text-center">
              <button type="button" class="btn btn-simple" data-dismiss="modal">Never mind</button>
              <a href="{{url_for('mtechs.allocate_mtech')}}"><button type="submit" class="btn btn-success btn-simple">Yes</button></a>
          </div>
      </div>
  </div>
</div>

<div class="row" style="justify-content: center;display: flex;">
  

    <button class="btn btn-raised btn-round btn-rose" data-toggle="modal" data-target="#smallAlertModalphd">
          Allocate Phd
      </button>
      
      <button class="btn btn-raised btn-round btn-rose" data-toggle="modal" data-target="#smallAlertModalmtech">
          Allocate Mtech
    </button>
    {% include 'uploadadd_top.html' %}
      </div>
                        
                        
    </div>
    
</div>
</div>
<div class="row" style="justify-content: center;display: flex;">
        

<a href="{{url_for('phds.phdcsv')}}"><button class="btn btn-raised btn-round btn-rose" >
Create phd database
</button></a>

<a href="{{url_for('mtechs.mtechcsv')}}"> <button class="btn btn-raised btn-round btn-rose" >
Create Mtech database
</button></a>
{% include 'uploadadd_bottom.html' %}
</div>
</div>
</div>
{% endblock content %}